/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDeviceRouteImport } from './routes/api/device'
import { Route as ApiPanelRouteImport } from './routes/api/panel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceRoute = ApiDeviceRouteImport.update({
  id: '/api/device',
  path: '/api/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPanelRoute = ApiPanelRouteImport.update({
  id: '/api/panel',
  path: '/api/panel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/device': typeof ApiDeviceRoute
  '/api/panel': typeof ApiPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/device': typeof ApiDeviceRoute
  '/api/panel': typeof ApiPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/device': typeof ApiDeviceRoute
  '/api/panel': typeof ApiPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/device' | '/api/panel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/device' | '/api/panel'
  id: '__root__' | '/' | '/api/device' | '/api/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDeviceRoute: typeof ApiDeviceRoute
  ApiPanelRoute: typeof ApiPanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device': {
      id: '/api/device'
      path: '/api/device'
      fullPath: '/api/device'
      preLoaderRoute: typeof ApiDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/panel': {
      id: '/api/panel'
      path: '/api/panel'
      fullPath: '/api/panel'
      preLoaderRoute: typeof ApiPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDeviceRoute: ApiDeviceRoute,
  ApiPanelRoute: ApiPanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
